//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 10:28:18 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.ns", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ns.schema;
