//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.15 at 10:37:58 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.sample/soapserver", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sample.com.soapserver;
